#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
//set this up
#include "images/square.h"
#include "images/white.h"
#include "images/squaregreen.h"
#include "images/easygame.h"
#include "images/circle.h"
#include "images/ggbro.h"
#include "images/youwin.h"
/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  DRAW,
  INIT,
  PLAY,
  WIN,
  LOSE,
  STOPDRAW,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        waitForVBlank();
        drawFullScreenImageDMA(easygame);
        drawCenteredString(110, 80, 80, 80, "Press ENTER", BLACK);
        state = DRAW;
        break;

        // state = ?
      case DRAW:
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = INIT;
          curr.timer.moves = 0;
          break;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          curr.timer.moves = 0;
          state = START;
        }
        break;

        // state = ?
      case INIT:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          curr.timer.moves = 0;
          state = START;
          break;
        }
        waitForVBlank();
        fillScreenDMA(WHITE);
        curr.player1.row = 3;
        curr.player1.col = HEIGHT-145;
        curr.player1.width = 15;
        curr.player1.height = 15;
        curr.enemy.col = HEIGHT - randint(10,120);
        curr.enemy.row = WIDTH - randint(15,200);
        curr.enemy.width = 15;
        curr.enemy.height = 15;
        curr.endpoint.row = 10 + randint(20,100);
        curr.endpoint.col = 10 + randint(20,150);
        curr.endpoint.width = 15;
        curr.endpoint.height = 15;
        state = PLAY;
        break;

      case PLAY:
        drawString(4, 5, "reach the goal bro (black square)", RED);
        drawString(150, 5, "the black rectangle-thing is bad bro", RED);
        char moves[6] = "000\0";
        moves[3] = (curr.timer.moves / 10) + '0';
        moves[4] = (curr.timer.moves % 10) + '0';
        drawString(3, 203, "Moves:", BLACK);
        drawRectDMA(208, 12,30,15,WHITE);
        drawString(15, 208, moves, BLACK);        
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
          curr.timer.moves = 0;
          break;
        }
        if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
          waitForVBlank();
          drawRectDMA(curr.player1.row, curr.player1.col, curr.player1.width, curr.player1.height, WHITE);
          curr.player1.row -= 5;
          curr.timer.moves++;
        }
        if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
          waitForVBlank();
          drawRectDMA(curr.player1.row, curr.player1.col, curr.player1.width, curr.player1.height, WHITE);
          curr.player1.row += 5;
          curr.timer.moves++;
        }
        if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
          waitForVBlank();
          drawRectDMA(curr.player1.row, curr.player1.col, curr.player1.width, curr.player1.height, WHITE);
          curr.player1.col -= 5;
          curr.timer.moves++;
        }
        if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
          waitForVBlank();
          drawRectDMA(curr.player1.row, curr.player1.col, curr.player1.width, curr.player1.height, WHITE);
          curr.player1.col += 5;
          curr.timer.moves++;
        }
        waitForVBlank();
        drawImageDMA(curr.player1.col, curr.player1.row, curr.player1.width,
          curr.player1.height, squaregreen);
        drawImageDMA(curr.endpoint.col, curr.endpoint.row, curr.endpoint.width,
          curr.endpoint.height, circle);
        drawImageDMA(curr.enemy.col, curr.enemy.row, curr.enemy.width,
          curr.enemy.height, square);
        if ((curr.player1.col <= (curr.endpoint.col + (15))) &&
            (curr.player1.col >= (curr.endpoint.col - (15))) &&
            (curr.player1.row >= (curr.endpoint.row - (15))) &&
            (curr.player1.row <= (curr.endpoint.row + (15)))) {
              state = WIN;
        } 
        if ((curr.player1.col <= (curr.enemy.col + (15))) &&
            (curr.player1.col >= (curr.enemy.col - (15))) &&
            (curr.player1.row >= (curr.enemy.row - (15))) &&
            (curr.player1.row <= (curr.enemy.row + (15)))) {
              state = LOSE;
        } 
        if ((curr.player1.col < 0 || curr.player1.col > 145 || curr.player1.row < -1 || curr.player1.row > 235)) {
          state = LOSE;
        }  
         break;

    case WIN:
      waitForVBlank();
      drawFullScreenImageDMA(youwin);
      char totalMoves[6] = "000\0";
      totalMoves[3] = (curr.timer.moves/10) + '0';
      totalMoves[4] = (curr.timer.moves % 10) + '0';
      drawString(40,20, "Total Moves:", GREEN);
      drawString(40, 100, totalMoves, GREEN);
      drawString(80, 25, "Nice bro", GREEN);
      drawCenteredString(100, 80, 80, 80, "ENTER: play agin", WHITE);
      curr.player1.score = 0;
      state = STOPDRAW;
      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
        state = START;
        curr.player1.score = 0;
        break;
      }
      break;
    case LOSE:
      waitForVBlank();
      drawFullScreenImageDMA(ggbroski);
      drawString(120, 100, "rip bro", RED);
      drawCenteredString(100, 80, 80, 80, "ENTER: play agin", WHITE);
      curr.player1.score = 0;
      state = STOPDRAW;
      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
        state = START;
        curr.player1.score = 0;
        break;
      }
      break;
      
    case STOPDRAW:
      if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
        vBlankCounter = 0;
        curr.player1.score = 0;
        state = START;
      }
      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
        state = START;
        curr.player1.score = 0;
        break;
      }
      break;
    }

    previousButtons = currentButtons; 
  }


  return 0;
}
